### ISSUE TITLE
posit cloud guide

### ISSUE THREAD

**Issue by shannonpileggi** [rladies/rladiesguide#100]
provide guidance on how to request posit cloud access and use

**Comment by maelle** [comment]
who knows about this? Could this person either make a PR or add notes here so I'd edit https://guide.rladies.org/organization/tech/accounts/ (unless it seems better to store the info somewhere else)?

**Comment by drmowinckels** [comment]
A couple of this issues are made by the leadership as reminders to our selves to make the content. This one is Shannon and myself :)

**Comment by maelle** [comment]
Ok! Let me add assignments to do tidy GitHub project management à la @drmowinckels :stuck_out_tongue_winking_eye:

**Comment by maelle** [comment]
> What do you think about separating it and moving event tooling (meetup & posit cloud) to events section?

Sounds good! 

So sorry for the huge delay :grimacing:
