### ISSUE TITLE
remove mentions to the heroku app for joining the Community Slack

### ISSUE THREAD

**Issue by rivaquiroga** [rladies/rladiesguide#102]

**Comment by drmowinckels** [comment]
related to #97

**Comment by maelle** [comment]
@yabellini @averigg should we already point to the new form? Could you please remind me of the link? Thank you!

**Comment by averigg** [comment]
yep! here is the link to the airtable form: https://airtable.com/appJZFYABfCIdPYMR/shrReqdN8fhuXGY3P

**Comment by yabellini** [comment]
Closing as states in #115
