### ISSUE TITLE
(minor) Link to blog post on first page broken

### ISSUE THREAD

**Issue by benjana** [rladies/rladiesguide#112]
Link to blog post in the note on this [page](https://github.com/rladies/rladiesguide/blob/main/content/_index.en.md) doesn't seem to go where intended: https://blog.rladies.org/post/reduced-service-note/ 

It's possible that the whole note is out of date at this point (?), but it's very prominent as it is at the very beginning

**Comment by maelle** [comment]
Thank you!!

**Comment by maelle** [comment]
Thanks again @benjana, it was a good catch! :pray:

**Comment by benjana** [comment]
Happy to help @maelle! :) I can keep an eye out as I read through the guide
