### ISSUE TITLE
link to organiser slack is broken

### ISSUE THREAD

**Issue by drmowinckels** [rladies/rladiesguide#114]
https://github.com/rladies/rladiesguide/blob/main/content/organization/online-presence/slack/index.en.md?plain=1#L7

But I'm not entirely sure where it should be pointing to.

**Comment by rivaquiroga** [comment]
Maybe to https://guide.rladies.org/organization/tech/accounts/#slack? I'll update this on https://github.com/rladies/rladiesguide/pull/115

**Comment by yabellini** [comment]
Closing as state in #115
