### ISSUE TITLE
Zenodo integration

### ISSUE THREAD

**Issue by drmowinckels** [rladies/rladiesguide#119]
Let make our work citable! 

idea is to:
- get a DOI from Zenodo
- release once a year (or more often is a large enough change occurs mid-year). 

We likely need to set up a nice zenodo json with some information:
https://github.com/ropensci/dev_guide/blob/main/.zenodo.json

**Comment by yabellini** [comment]
@drmowinckels should we close this issue?

**Comment by drmowinckels** [comment]
completed with https://github.com/rladies/rladiesguide/commit/acd6adcd0ab83c6b683eebc7c645301efd6d82b0
