### ISSUE TITLE
Add "thank you notes" tips?

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#12]
* When do you thank people (after they helped, later in a batch e.g. around the holidays)
* Who do you thank (speakers, sponsors, random helpers)
* How do you keep track of who to thank
* How do you send notes (emails? if snail mail how do you safely collect addresses? if snail mail what kind of card/paper do you use?)
* Any thank-you template?

**Comment by kfettich** [comment]
**When do you thank people?** We send Thank You cards at the end of the year
**Who do you thank?** Everyone who has helped with organizing an event (speakers, sponsors, organizers from other groups if it's a collaboration effort) 
**How do you keep track of who to thank?** We keep a google spreadsheet listing name, support type, email address, postal address, who's responsible for sending it, and status of the thank you card (sent/not sent)
**How do you send notes?** We send thank you cards via snail mail; we design them ourselves, usually showing our chapter's accomplishments over the year, then have them printed via an online service and mailed to one of us; we then hand-write a thank you note to the recipient, thanking them for their specific contribution to our chapter's success, and apply stamps and drop them in the mail; the type of card depends on the budget we have available; we try not to splurge, but try to add a sticker or other small token of appreciation as well when possible; in terms of addresses, we usually look up the recipients' work address, unless we know a more direct way of getting the thank you card to them 
**Any thank-you template?**: https://twitter.com/minebocek/status/1082488324282109952?s=20

**Comment by maelle** [comment]
thanks @kfettich and this is awesome!!
