### ISSUE TITLE
intergroup events recommendations - host on meetup?

### ISSUE THREAD

**Issue by shannonpileggi** [rladies/rladiesguide#125]
In our guidelines for [inter group events](https://guide.rladies.org/organization/events/general/#inter-group-events) the example provided states:

> Because this was open to folks beyond R-Ladies, Ashton agreed to host the event via her own Eventbrite account, rather than R-Ladies RTP organizers using the chapter’s Meetup page. 

However, then that chapter will not get "credit" for the event to count towards chapter activity.

Should we have a general recommendation that intergroup events be hosted on meetup and/or mutliple platforms where applicable? Or just caveat that if the event is not hosted on meetup it will not count towards chapter activity.

**Comment by shannonpileggi** [comment]
K I can create a PR to make that clear.

I am not sure - should we modify the text of the example provided? or leave as-is?

**Comment by yabellini** [comment]
We need to change the example because it is not aligned with our current advice.
