### ISSUE TITLE
Add instructions how to add new co-organizers

### ISSUE THREAD

**Issue by cosimameyer** [rladies/rladiesguide#128]
Here's a section on co-organizers: add instructions on how to add them here as well ☺️

https://guide.rladies.org/organization/intro/co-organizers/

FYI: @MounaBelaid I believe you know best what's the procedure (and we can update it with the link to the new form once it's confirmed it's running)

**Comment by drmowinckels** [comment]
Duplicate of #18

**Comment by cosimameyer** [comment]
I’ll go ahead and close it since it’s a duplicate. I’ll be referenced in the other issue stream anyway.

**Comment by cosimameyer** [comment]
This is what I wanted to do ☺️

**Comment by cosimameyer** [comment]
I’ll go ahead and close it since it’s a duplicate. I’ll be referenced in the other issue stream anyway.

**Comment by cosimameyer** [comment]
I’ll go ahead and close it since it’s a duplicate. I’ll be referenced in the other issue stream anyway.
