### ISSUE TITLE
last updated information

### ISSUE THREAD

**Issue by shannonpileggi** [rladies/rladiesguide#145]
Should we indicate when information on the guide was last updated somehow?

Some ideas:

1. `NEWS.md` that tracks updated changes moving forward
2. a tip box that gets added to each index when updated that autmatically pulls in the date of update.

Something else?

**Comment by drmowinckels** [comment]
you mean for any commit, or for each release?

**Comment by shannonpileggi** [comment]
up for debate! just to give context to readers. for example, this came up in the discussion of updated guidelines for zoom bombers.  for software specific things like that, does knowing the last time something was updated help the reader? as defaults and policies can change over time.

**Comment by drmowinckels** [comment]
Hugo has the option to show information about last commited changes to a file. We can add that to the pages. That would be the most accurate, right ?

tagging @maelle as she set it up and might now how easy/hard it would be to get set up.

**Comment by maelle** [comment]
NEWS.md would make sense but a) is a lot of work b) might not be read.

Adding the date and time could work with Git info and a custom layout, not too much work once we decide where it goes. https://gohugo.io/methods/page/gitinfo/#authordate

Would bottom-right make sense?

**Comment by shannonpileggi** [comment]
yeah i agree re news. still could be helpful moving forward.

not sure about bottom right as some pages are so long?? no strong preference though.

**Comment by maelle** [comment]
will try to implement something soon!

**Comment by maelle** [comment]
#146
