### ISSUE TITLE
Add infos about managing an IWD campaign

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#15]
As suggested by @yabellini

Are the blog posts the only notes that exist at the moment?

**Comment by maelle** [comment]
Goals

> Interest more people who want to join the project.
    Explain how you can collaborate.
    Collect more ideas for future campaigns.
    Inspire other types of local or regional chapter campaigns.
    Inspire campaigns from other communities.

**Comment by yabellini** [comment]
Some more info here: https://github.com/rladies/IWD

**Comment by maelle** [comment]
Thanks a ton. I'll push a commit adding a chapter and close this issue. We can still come back to the chapter to improve it afterwards.
