### ISSUE TITLE
add links to resources that are not datacamp

### ISSUE THREAD

**Issue by labouz** [rladies/rladiesguide#19]
i love that this resource was added:https://guide.rladies.org/about/datacamp/
it would be nice to supplement this with alternative resources for people who are new to R/
happy to help with this :)

**Comment by maelle** [comment]
Good idea, thank you! 

I'd like to link to https://www.learnr4free.com/index.html and such "aggregators" in order not to manage a list of courses ourselves if that makes sense? Do you know of other such collections of links?

**Comment by labouz** [comment]
yes! thats a great one. hmm...
maybe https://education.rstudio.com/learn/
https://www.adventures-in-r.com/ or
https://www.bigbookofr.com/index.html

**Comment by labouz** [comment]
i've bookmarked so many threads on twitter so i'll go through and see which are not included in the learnrforfree list

**Comment by chucheria** [comment]
It is not exacly learn but a good resource: https://rstudio.com/resources/cheatsheets/
And https://github.com/qinwf/awesome-R

**Comment by yabellini** [comment]
https://yabellini.shinyapps.io/RLadiesLesson/

**Comment by maelle** [comment]
@yabellini btw I was wondering, is it continuously updated? (even if it weren't, it'd still be an awesome resource)

**Comment by yabellini** [comment]
I don't have time for an update (last update March 2020).  But, it is what I want to do in the future for R-Ladies, so maybe next year I will be able to work on this, including move this app to R-Ladies domain and not be anymore in my personal space.

**Comment by maelle** [comment]
We should talk, I wonder whether it could be automated a bit :thinking:

**Comment by yabellini** [comment]
There is an automated part, but not all and there is a lot of room for improvement.  Yes, please, let's talk!

**Comment by labouz** [comment]
> It is not exacly learn but a good resource: https://rstudio.com/resources/cheatsheets/
> And https://github.com/qinwf/awesome-R

on that one, here is an awesome list of shiny resources! https://github.com/grabear/awesome-rshiny

**Comment by maelle** [comment]
See https://guide.rladies.org/organization/resources/learning-r/ (and @labouz your name is now listed in https://guide.rladies.org/acknowledgements/, thanks again)
It is listed from the DataCamp disapproval page.

If you have further suggestions of links to add, feel free to make a PR / open a new issue.

**Comment by maelle** [comment]
Thanks @chucheria @yabellini too :-)

**Comment by labouz** [comment]
Beautiful, thank you @maelle !
