### ISSUE TITLE
Assess use of current-chapters.csv

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#2]
@yabellini @ledell if processes involving the CSV change I'll need to update quite a few sections cf https://github.com/rladies/rladiesguide/search?q=current-chapters.csv&unscoped_q=current-chapters.csv

**Comment by ledell** [comment]
@maelle Did someone say that the processes are going to change?  I think we are still using it as our source of truth -- is that correct, @yabellini?

**Comment by maelle** [comment]
yes but wasn't there some discussion around trying to not make "being able to do a PR" necessary?

**Comment by yabellini** [comment]
Yes for our source of truth, and I remember the discussion because most of the time the update and / or the PR ends up being done by one of the Global Team people.  But, for now, that I know, we don't change this workflow.
