### ISSUE TITLE
How do we expect organizers to manage passwords?

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#20]
We tell organizers to e.g. set up Twitter/Facebook using the chapter email address.

Now, how do we expect them to share _access_ to these accounts? Do they simply share a password and try to renew it often? If a single person manages the Twitter account with 2FA, where are the recovery codes for 2FA stored in case this person unexpectedly disappears?

For Twitter, with Tweetdeck you can add users to an account without their knowing the password.

**Comment by paocorrales** [comment]
We have an (very unsafe) shared doc with all the passwords. We manage the access to the doc but we don't change password often. 

I would like to know if there a better way to manage passwords!

**Comment by maelle** [comment]
@paocorrales thank you! can you write for which services you need to share passwords by the way?

E.g. for Twitter you can grant access to an account to Twitter users via Tweetdeck, e.g. you'd grant access to `@rladiesba` to `ma_salmon` so `ma_salmon` could tweet for `rladiesba` without knowing the password.

But such features don't exist for all services. I think ultimately we could have guidance for password management in particular, and some services in particular. :thinking:

**Comment by paocorrales** [comment]
We share passwords to manage our Instagram account and our YouTube channel but I believe that you can grant access to YouTube using personal emails.

**Comment by maelle** [comment]
Thanks!

Writing down some things I was thinking about. Even if an account grants write access to users, one still needs someone with admin rights. Say the account email address is rladiesba@rladies.org. One person sets up the password and saves it in their password manager (e.g. I use keepass). Now if something happens to this person, another person with access to rladiesba@rladies.org can simply write "forgot my password". However, this does not work if one adds 2FA to the service, because 2FA is linked to one device. In that case one would need to store the recovery codes of 2FA somewhere safe and central.

Something like bitwarden is probably too expensive https://bitwarden.com/pricing/business/ (and setting it up ourselves on a server isn't free either, as it requires someone's time, and several people would need to be involved to reduce the bus factor).

I still think we should try and come up with some good guidance for all chapters.
