### ISSUE TITLE
A really nice talk about community of practices

### ISSUE THREAD

**Issue by yabellini** [rladies/rladiesguide#41]
I rewatch this talk by Kate Hertweck (which is awesome), and I think that is an excellent talk to recommend to watch to organizers: https://rstudio.com/resources/rstudioconf-2020/if-you-build-it-they-will-come-but-then-what-facilitating-communities-of-practice-in-r/

**Comment by maelle** [comment]
Thanks a lot (I liked this talk too!), added a new section for this, so if you have other suggestions they can be featured. :wink:
