### ISSUE TITLE
Clarify non-commercial agenda a bit more in Rules & Guidelines

### ISSUE THREAD

**Issue by ledell** [rladies/rladiesguide#43]
We used to have this text: https://github.com/rladies/starter-kit/commit/96941dafba8863ad8ef29037f672856aa366123a

Now this paragraph is more generalized and expanded a bit, but maybe we can add a sentence or two to explain further (give some examples of allowed vs not allowed commercial co-mingling): https://guide.rladies.org/about/mission/#r-ladies-rules--guidelines

**Comment by maelle** [comment]
Oops, good catch!!
