### ISSUE TITLE
Add more information about how to set up a chapter twitter account

### ISSUE THREAD

**Issue by ledell** [rladies/rladiesguide#44]
Can we add some more specific instructions for how to set up a chapter twitter account on the [Social Media](https://guide.rladies.org/organization/online-presence/social-media/) page?  I find it helpful to point people to the page where they can edit their username and also to provide logos that they can use for the profile pic (unless/until they have their own custom chapter logo).

Here's what we say on the WiMLDS Starter Kit, as an example:  https://github.com/WiMLDS/starter-kit/wiki/Start-a-new-chapter#the-following-steps-are-optional-but-encouraged

**Comment by maelle** [comment]
Isn't it in https://guide.rladies.org/organization/online-presence/social-media/#twitter?

**Comment by ledell** [comment]
@maelle Oops... Somehow I totally missed that.  I saw the top of the page referencing twitter but I forgot that we had a whole section about it below.  I guess the only improvement I can think of now is to add the direct links to the place where you edit the name and username on Twitter (like we do in the WIMLDS page).  I can do that if you like?

**Comment by maelle** [comment]
Yes that'd be great! Thanks!

Also feel free to suggest structure improvements if the info was hard to find.

**Comment by maelle** [comment]
@ledell sorry for closing this, I misread the thread! Your PR is still welcome.
