### ISSUE TITLE
Gracias don't need orthographic accent - and more informal message

### ISSUE THREAD

**Issue by yabellini** [rladies/rladiesguide#50]
The word Gracias in Spanish does not have an orthographic accent:

https://guide.rladies.org/acknowledgements/

This message can be less formal (I don't know how we want this sound, so it is a suggestion):

Original: _Si contribuyó al contenido y olvidamos añadir su numbre, lo sentimos mucho. Por favor abra una “issue” en el repositorio y lo añaderimos._

Suggestion: Si contribuiste al contenido y olvidamos añadir tu nombre, lo sentimos mucho.  Por favor abre un "issue" en el repositorio y te agregaremos. 

Also, I will make a link in the word issue to the issues on the repo.

**Comment by maelle** [comment]
Gracias!!
