### ISSUE TITLE
Clarify what meetups is

### ISSUE THREAD

**Issue by yabellini** [rladies/rladiesguide#51]
This comment comes from a new organizer (Nerissa Mulligan) on Slack when she is trying to create a new chapter and found the info "confusing and overwhelming" (I think we are having some "expert blind spot" here about platforms):

_It would be extremely helpful to add that one line “Meetup is a platform used to announce events” under the Meetup heading in the guide. Because I had never heard of it, I thought it was talking about meetups (as in “having a meeting”). And then when you said we had to use it because activity is tracked by RConsortium, I thought it was a platform for actual having the meetup (like zoom or skype). A quick line about what Meetup is and what it is used for would be great for new people who are not familiar with it._

**Comment by maelle** [comment]
Thank you @yabellini for opening the issue!
