### ISSUE TITLE
Add update about how new chapter emails are forward-only email accounts

### ISSUE THREAD

**Issue by ledell** [rladies/rladiesguide#52]
Let's maybe shorten this (below) and make a note in the guide [here]( https://guide.rladies.org/organization/tech/accounts/#e-mail).  Organizers are not aware that the new emails are forward-only.  Unless we get a new email provider, this will be the case.  This is what we have been doing since Dreamhost made the decision to limit new accounts to either full email *or* forwarding (but not both, as we had previously been using them).

> New chapter emails are just forwarding addresses (some of the earlier chapters have actual email accounts but that ended up being too difficult too much overhead to maintain and our hosting provider changed the policy that an email can only be a regular email OR a forwarding email, not both).  We found that most people were forwarding the chapter emails to their personal email addresses anyway.  So there’s no inbox or password.  The idea with the chapter email address is that you can use this as a public facing email address for your community, so members or companies or whoever can get in touch with you easily without you having to list a personal email address publicly.  Then you can use your personal email address to reply.

**Comment by ledell** [comment]
I've assigned myself, but if anyone else wants to add this, feel free.

**Comment by maelle** [comment]
A PR would be most welcome as you know the context better. :wink: :email: :pray:

**Comment by maelle** [comment]
You can make the text that's between parentheses a footnote, by the way.
