### ISSUE TITLE
Link to email page is a 404

### ISSUE THREAD

**Issue by ledell** [rladies/rladiesguide#53]
The tech infrastructure [email section](https://guide.rladies.org/organization/tech/accounts/#e-mail) links to "how use your rladies.org email in a mail client or within Gmail" but the page is a 404.  It's a cute 404 page though. :-) 

@maelle ~Do you know what happened to this page?~  https://guide.rladies.org/organization/email/

Edit: Ok, sorry i think this is just a typo in the URL and is supposed to link here: https://guide.rladies.org/organization/tech/email/

**Comment by maelle** [comment]
Thank for catching this!
