### ISSUE TITLE
add info on dead name updates for directory

### ISSUE THREAD

**Issue by sheilasaia** [rladies/rladiesguide#57]
draft text:
## Updating Dead Names

When updating an existing R-Ladies member directory profile, we usually edit the entry but this will not fix the URL. As a result, the dead name will still appear in the URL for the directory entry. Therefore, when requested to update a dead name in an existing directory entry, we will need to completely delete the old entry and add the entry as a new entry. This will create a new URL with the updated name.

**Comment by maelle** [comment]
@sheilasaia btw do you add some sort of redirect?

**Comment by sheilasaia** [comment]
@maelle, I don't think so....but it's possible that I messed something up when I tried to pull changes. I'm sorry but I'm not too experienced with collaborating with people other than myself on GitHub. 😅 I hope I didn't mess anything up. If I did, do you know how to fix it? I'm happy to meet over Zoom if that's easier!

**Comment by maelle** [comment]
I mean, in Wordpress, can one make it so so that the old entry redirects to the new entry? I think it's useless to explore now, as there'll be new ways to do redirects with Netlify. Now, I don't know whether it's a good idea to actually store redirects as it means there's a list of dead names in a public repo? So probably best not to redirect actually? Cc @Athanasiamo

**Comment by Athanasiamo** [comment]
I'd like to avoid keeping dead names around unless we (and the people in question) really want/need them.

1. keeping dead names outs people.
2. some have strong negative feelings to their dead names


technically, for the future website, none of directory is public in the repo, so we could in theory make some solution in the backend that might deal with this without saving the redirects in the repo it self, but that would still likely make the deadnames available through scraping... I think? 

Just thinking aloud. The private directory repo jsons could include a redirect field, and if that exists a redirect file could be generated by github actions when hugo builds and never committed. so no saving them to repo. 

The question is also f we want to do this, and what caveats this might bring. Some might like it, others might not. I'd like us to maybe hear with some we know this would have pertained to and get their opinions.

**Comment by maelle** [comment]
so probably no redirect sounds the best? thanks a ton for your advice!

**Comment by maelle** [comment]
so probably no redirect sounds the best for now? thanks a ton for your advice! (but yes to getting other opinions!)

**Comment by Athanasiamo** [comment]
also! for the new website, people dont get their own pages. ALl directory information for a person is in their cards. So no need for a redirect. This stos us from being able to share links to a specific directory entry though, so might be something to consider... thats just going to be _a lot_ of static pages

**Comment by maelle** [comment]
Isn't Hugo meant for huge sites? :wink:

Wouldn't IDs help linking to a person e.g. rladies.org/directory#athaniasia-mowinckel and if the name change then people still land on rladies.org/directory.

**Comment by Athanasiamo** [comment]
very true. hugo is hugo, this is what it does right? I just had not thought of it! I'll put it on the list of things to do/explore. 

definitely helps linking. I really just didnt think of it! So, I'll have a look at fixing that :)

**Comment by sheilasaia** [comment]
Ah I see what you were asking, @maelle. I think the redirect is fine as long as there's no mention of the deadname anywhere in the redirection (including URL, etc.). @Athanasiamo, I think it's a really good idea to talk to some folks from the community about what this could look like. In the mean time, we have already talked about what we'd do to delete someone's entry and add a new one for the new website (to be GDPR complaint) so I think that would apply in this case. Is that what you were thinking?
