### ISSUE TITLE
Recognising Contributions

### ISSUE THREAD

**Issue by yabellini** [rladies/rladiesguide#6]
I think this guide is also a good excuse to discuss how we are going to recognizing contributions to this o to other material made/host by R-Ladies.

I think we need clear rules about this, and I also think that being volunteers we need to be able to show what we do for the community, so we can show our tasks and responsibilities and not only when we are an active part, but always.
It's fair and in this way, there is one more incentive for people to contribute.

Here are nice examples to see:
https://github.com/all-contributors/all-contributors
https://allcontributors.org/docs/en/bot/usage
https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md

**Comment by maelle** [comment]
I also wonder how we can do that given that I've committed stuff written by other people. (i.e. we can't really trust the git history)

In the rOpenSci dev guide, the changelog is complete, and there's also a curated list of contributors.

I could start adding the names of all global team members, former and current?

**Comment by maelle** [comment]
So what about 

* I add names of all global team members, former and current

* I make a rule to add names of future contributors

* I add a sentence about if we missed your name, please tell us
