### ISSUE TITLE
Web page and repos for countries ?

### ISSUE THREAD

**Issue by yabellini** [rladies/rladiesguide#7]
Here we talk about webpages for chapters https://r-ladies-guide.netlify.app/organization/online-presence/website/

But there is not mention to webpages for countries, but some exist: https://rladiesmx.netlify.app/

and also repos (some examples):

* https://github.com/rladieschile

* https://github.com/rladiesnl

* https://github.com/RLadiesEnArgentina

The COVID19 helped many chapters to join forces to organize meetups, so it also happened with #rladiesitaly and #rladiesecuador for example

I think is a good idea to allow country web pages as RLadies **in** name of the country.  For people in LatAm also means that we can have a web page in our language and is it more easily keep a single web that nine. If not, again, chapters in larger cities have more advantages.  It would also be a single common point to contact us.

**Comment by maelle** [comment]
In the case where a meetup is organized by several chapters, who could help me write guidance about how to tackle that? I.e. how does one promote the event and how do chapters "share" spots?

So the topic of inter-chapters (most often by country, but could be by some other thing) would be
* common website
* common social media channels
* how to organize an event together
