### ISSUE TITLE
Add section about using R-Ladies in grant proposals

### ISSUE THREAD

**Issue by ledell** [rladies/rladiesguide#73]
There was a case where the R-Ladies name was used in a grant proposal to potentially help secure funding (promising benefits to R-Ladies).  However, this was done without any coordination or communication with the R-Ladies Global team.

Let's add a section in [Partnerships](https://guide.rladies.org/organization/intro/partnerships/) (or maybe [Allies](https://guide.rladies.org/ally/)?) to let people know they should contact us at info _at_ rladies.org when doing this so we know about it and can provide input/approval.  We want to make sure that it's an organization that is in alignment with our mission.

**Comment by maelle** [comment]
Would adding a sentence to the last section of https://guide.rladies.org/ally/ be enough or do we want something more central?

**Comment by ledell** [comment]
@maelle Yeah, I think that makes sense.  Thanks!
