### ISSUE TITLE
Recommend better tweetdeck to rocur curators?

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#77]
https://twitter.com/noamross/status/1529098820633919488

Cc @katherinesimeon  @shannonpileggi (I could not find Emmanuelle Nunes' username)

**Comment by shannonpileggi** [comment]
Thank you, @maelle! I'm not convinced this offers a lot of functionality above and beyond regular tweetdeck (like threads), but I can explore more.

**Comment by shannonpileggi** [comment]
We looked a bit further and we don't think the additional functionality is worth the installation. If anyone can find a tweetdeck that better supports threads please let us know.
