### ISSUE TITLE
WeAreRLadies expand Tweeting Tips 

### ISSUE THREAD

**Issue by shannonpileggi** [rladies/rladiesguide#78]
https://guide.rladies.org/rocur/guide/#tweeting-tips

Introducing yourself -> add your twitter handle

Add section on saying goodbye

**Comment by maelle** [comment]
More on alternative text? https://twitter.com/spcanelon/status/1570888033238667264

**Comment by shannonpileggi** [comment]
We have a PR open https://github.com/rladies/rladiesguide/pull/80, please let us know if you see other clarifications we can make.

**Comment by maelle** [comment]
See also https://twitter.com/DogGeneticsLLC/status/1571927798784073728

**Comment by shannonpileggi** [comment]
We could research if there are browswer extensions for tweetdeck to remind users to include alt text. Of course, that would be browser specific and users might not install it.

We could also provide stronger wording around expectations to include alt text.

**Comment by shannonpileggi** [comment]
also this suggestion, we can follow this account from @WeAreRLadies and document that we are doing so to prompt the sender to provide alt text after the fact if forgotten 

https://twitter.com/Letxuga007/status/1572972055695618048?s=20&t=YZ_rkAbDawFxQzlF0EYONQ

**Comment by shannonpileggi** [comment]
PR #80 was merged, but there is still room to improve alt text documentation so leaving this open.

@spcanelon if you have time to look at this any suggestions would be much appreciated!

**Comment by maelle** [comment]
Can we close this @shannonpileggi?
