### ISSUE TITLE
why is the CoC page rendering text?

### ISSUE THREAD

**Issue by drmowinckels** [rladies/rladiesguide#95]
The [coc.md](https://github.com/rladies/rladiesguide/blob/main/content/about/coc/index.en.md) contains only a link to the CoC on the website, but the [rendered version](https://guide.rladies.org/about/coc/) includes the entire coc? Where is that coming from?

**Comment by drmowinckels** [comment]
found it!
https://github.com/rladies/rladiesguide/blob/main/layouts/coc/single.html#L4-L5

That content is actually also supposed to change, now that its being rendered on the website. The .github coc should point to the website version, so we can maintain a single entry point.

**Comment by drmowinckels** [comment]
ok, I reminded myself what was going on, and sorry for making a confusing issue. 
Lets keep as is, untill be get portuguese and spanish translations of the website. 
Then we can redo this linking a little, and render from the website repo rather than the .github repo?

https://github.com/rladies/rladies.github.io/tree/main/content/coc

**Comment by drmowinckels** [comment]
or we could technically link to the rendered english version already?

**Comment by maelle** [comment]
thank you, good catch!
