### ISSUE TITLE
co-hosted events

### ISSUE THREAD

**Issue by shannonpileggi** [rladies/rladiesguide#99]
provide considerations for co-hosted events (PyLadies, RUG, useR, >=2 R-Ladies chapters)

some thoughts from slack:
Are they a PyLadies chapter?
 If yes, then they can use R-Ladies and PyLadies And try to be clear on which CoC they apply

There are a couple of things to take into consideration:
PyLadies is an organization that has their own guidelines/workflow to create chapters. Is not on our behalf to decide if they can use the brand. AFAIK, there is no PyLadies chapter in Ottawa (unless they haven’t registered it yet on the official website). So they should go through that process if they want to use the brand.
PyLadies has a different policy regarding organizers: “Ideally the organizers in your group should be women or women majority”. So technically, you can have a cis man as part of the organizing team.
PyLadies is more flexible about the platform you use to organize events, mainly because they don’t offer a Meetup Pro account by default. You have to apply as a chapter for reimbursement if your subscription is more than 90 dollars per 6 months. We, on the other hand, offer that to every chapter and currently don’t allow chapters to exist outside our Meetup Pro account.
AFAIK, PyLadies doesn’t have a policy regarding chapter inactivity.

**Comment by maelle** [comment]
We currently have https://guide.rladies.org/organization/events/general/#inter-group-events so that'd be the place to edit I think.

Would you like to make a PR @shannonpileggi?

**Comment by shannonpileggi** [comment]
Yes, happy to start one!

**Comment by shannonpileggi** [comment]
We are also planning this as a discussion topic at the posit conf rladies reception so we might get more ideas to add from there as well.
